language: go
sudo: false
before_script:
    - go get github.com/mattn/goveralls
script:
    - go test ./... -covermode=count -coverprofile=c.out
    - goveralls -coverprofile=c.out -service=travis-ci -repotoken $COVERALLS_TOKEN
go:
    - 1.8
    - 1.9
    - tip

